name: Daily CurrentAffairs Scraper

on:
  schedule:
  # Attempt 1: 9:00 AM IST (3:30 AM UTC)
  - cron: '30 3 * * *'
  # Attempt 2: 10:00 AM IST (4:30 AM UTC)
  - cron: '30 4 * * *'
  # Attempt 3: 11:00 AM IST (5:30 AM UTC)
  - cron: '30 5 * * *'
  # Attempt 4: 12:00 PM IST (6:30 AM UTC)
  - cron: '30 6 * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab in GitHub

jobs:
  scrape_and_generate_report:
    runs-on: ubuntu-latest # Use a Linux environment provided by GitHub
    permissions: 
      contents: write   # This allows the GITHUB_TOKEN to push to the repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checks out your repository code

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install wkhtmltopdf and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf xvfb libjpeg-turbo8 fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxrender1 libfontconfig1 libxext6

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run the scraper script
        run: python main.py

      - name: Upload PDF report as artifact
        if: success() 
        uses: actions/upload-artifact@v4
        with:
          name: daily-news-report-pdf
          path: Output Pdf/*.pdf 
          if-no-files-found: warn 

      - name: Upload HTML report and images as artifact
        if: success() 
        uses: actions/upload-artifact@v4
        with:
          name: daily-news-report-html-images
          path: |
            Output Html/*
            Output Images/*
          if-no-files-found: warn
      
      # --- Commit and Push the Generated Report Back to the Repository ---
      - name: Commit and Push Report
        if: success() 
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@users.noreply.github.com'
          git add Output\ Pdf/\* Output\ Html/\* Output\ Images/\*
          if ! git diff --staged --quiet; then
            git commit -m "Automated daily report for $(date +'%Y-%m-%d')"
            git push
          else
            echo "No changes to output files to commit."
          fi
